### ISSUE TITLE
mail: mail@mail.com  vs username: mail@mail.com

### ISSUE THREAD

**Issue by ManTreff** [Danielhiversen/home_assistant_petcare#2]
Hi,
thanks for the job.

Because i cant find petcare in HACS, i past files.

but the good syntax in configuration.yaml is:

petcare:
  mail: mail@mail.com
  password: 'pswd'

This make error:
petcare:
  username: mail@mail.com
  password: 'pswd'

**Comment by IainPHay** [comment]
Same issue, does not show to add from integrations whether it is installed via hacs or pasting the files into custom components.

petcare:
mail: mail@mail.com
password: 'pswd'

or

petcare:
mail: mail@mail.com
password: pswd

or

petcare:
mail: 'mail@mail.com'
password: 'pswd'

All fail.

**Comment by Danielhiversen** [comment]
Thanks, have updated the docs now.
Here is how you can install it from hacs: https://hacs.xyz/docs/faq/custom_repositories/ (Will add the link to readme)

**Comment by IainPHay** [comment]
Hi Daniel

I have done exactly this and installed via Hacs already and cannot add it via add integration from the configuration integrations section or via the config file. Doesn’t help unfortunately I wonder if some residual config is left over from the previous integrations which is causing an issue?


Iain

**Comment by Danielhiversen** [comment]
Strange.
Any errors in the log?
